import Head from "next/head";
import styles from "@/styles/Home.module.css";

import { Card } from "../components/Card/card";
import { TextFieldLabel } from "../components/FormField/index";
import IconButton from "@/components/IconButton";
import ProfileIcon from "@/components/icons/ProfileIcon";
import {BigStat} from "@/components/BigStat/bigStat";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${styles.main}`}>
        <TextFieldLabel state='default' text='my label' />
        <TextFieldLabel state='active' text='my label' />
        <TextFieldLabel state='disabled' text='my label' />
        <TextFieldLabel state='error' text='my label' />

        <div className={styles.flexWrap}>
          <IconButton size='small'>
            <ProfileIcon />
          </IconButton>
          <IconButton size='small' state='active'>
            <ProfileIcon />
          </IconButton>
          <IconButton size='small' disabled>
            <ProfileIcon />
          </IconButton>
        </div>
        <div className={styles.flexWrap}>
          <IconButton>
            <ProfileIcon />
          </IconButton>
          <IconButton state='active'>
            <ProfileIcon />
          </IconButton>
          <IconButton disabled>
            <ProfileIcon />
          </IconButton>
        </div>
        <div className={styles.flexWrap}>
          <IconButton display='empty'>
            <ProfileIcon />
          </IconButton>
          <IconButton display='empty' state='active'>
            <ProfileIcon />
          </IconButton>
          <IconButton display='empty' disabled>
            <ProfileIcon />
          </IconButton>
        </div>
        <Card
          title='Card title'
          description='This is a card description'
          badgeText='experiment'
          infoText='Read More'
          infoUrl='#'
        ></Card>
          <BigStat label={'Last successful backup'} largeValue={'12 hours ago'}></BigStat>
      </main>
    </>
  );
}
