import { useState } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";

import { Card } from "../components/Card/card";
import { TextFieldLabel } from "../components/FormField/index";
import { ButtonGroup } from "../components/ButtonGroup";

export default function Home() {
  const [selectedButton, setSelectedButton] = useState(0);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <TextFieldLabel state="default" text="my label" />
        <TextFieldLabel state="active" text="my label" />
        <TextFieldLabel state="disabled" text="my label" />
        <TextFieldLabel state="error" text="my label" />

        <Card
          title="Card title"
          description="This is a card description"
          badgeText="experiment"
          infoText="Read More"
          infoUrl="#"
        ></Card>

        <ButtonGroup
          labels={["Left center", "Center", "Center", "Center", "Right end"]}
          activeIndex={selectedButton}
          onClick={(index: number) => setSelectedButton(index)}
        />
      </main>
    </>
  );
}
