import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import { TextFieldLabel } from "../components/FormField";

const inter = Inter({ subsets: ["latin"] });

export default function Label() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <TextFieldLabel state="default" text="My Label" />
        <TextFieldLabel state="active" text="My Label" />
        <TextFieldLabel state="disabled" text="My Label" />
        <TextFieldLabel state="error"  text="My Label" />
      </main>
    </>
  );
}
