import Head from "next/head";
import { Inter } from "next/font/google";
import ClientComponent from "@/components/ClientComponent";

const inter = Inter({ subsets: ["latin"] });
export default function Demo() {
  return (
    <>
      <Head>
        <title>Demo page with ClickUI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ClientComponent />
      </main>
    </>
  )
};
