FROM mcr.microsoft.com/playwright:v1.60.0-noble

WORKDIR /app

RUN corepack enable && corepack prepare yarn@4.5.3 --activate

COPY package.json yarn.lock .yarnrc.yml ./

RUN yarn install

COPY . .

CMD ["npx", "playwright", "test"]
