// ============================================================================
// TYPE UTILITIES
// ============================================================================
// Utility types for working with design tokens and theme objects

/**
 * Prettify - Expands object types in IDE tooltips for better readability
 * Recursively flattens intersection types to show the actual structure
 */
export type Prettify<T> = {
  [K in keyof T]: T[K] extends object ? Prettify<T[K]> : T[K];
} & {};

/**
 * GetTypes - Extracts TypeScript types from JSON token values
 * Recursively traverses the token object and infers proper types
 * Handles arrays and nested objects correctly
 */
export type GetTypes<T> = Prettify<
  T extends (infer U)[]
    ? { [I in keyof T]: U extends object ? GetTypes<U> : U }
    : T extends object
      ? {
          [K in keyof T]: T[K] extends (infer U)[]
            ? { [I in keyof T[K]]: U extends object ? GetTypes<U> : U }
            : T[K] extends object
              ? GetTypes<T[K]>
              : T[K];
        }
      : T
>;

// ============================================================================
// THEME TYPES - Re-export from theme/index.ts
// ============================================================================
// This file exists for backward compatibility with components that import
// from "@/theme/tokens/types". The actual type definitions now live in
// theme/index.ts where they are derived directly from token values.
//
// Types are no longer generated by Style Dictionary. Instead, we use TypeScript's
// `typeof` operator with the GetTypes utility to extract types from the actual
// token values. This ensures types are always accurate and in sync.
// ============================================================================

export type { CUIThemeType as Theme } from "../index";
export type { ThemeName, PublicTheme } from "../index";
