// ============================================================================
// TYPE UTILITIES
// ============================================================================
// Utility types for working with design tokens and theme objects

/**
 * WidenLiteral - Converts literal types to their base types
 * - string literals → string
 * - number literals → number
 * - boolean literals → boolean
 * - preserves other types as-is
 */
type WidenLiteral<T> = T extends string
  ? string
  : T extends number
    ? number
    : T extends boolean
      ? boolean
      : T;

/**
 * GetTypes - Extracts TypeScript types and widens literals
 * Recursively traverses the object and widens literal types
 * Preserves readonly modifiers but widens string/number/boolean literals
 */
export type GetTypes<T> = {
  [K in keyof T]: T[K] extends (infer U)[]
    ? WidenLiteral<U>[]
    : T[K] extends object
      ? GetTypes<T[K]>
      : WidenLiteral<T[K]>;
};

/**
 * Prettify - Expands object types in IDE tooltips for better readability
 * Recursively flattens intersection types to show the actual structure
 */
export type Prettify<T> = {
  [K in keyof T]: T[K] extends object ? Prettify<T[K]> : T[K];
} & {};

// ============================================================================
// THEME TYPES - Re-export from theme/index.ts
// ============================================================================
// This file exists for backward compatibility with components that import
// from "@/theme/tokens/types". The actual type definitions now live in
// theme/index.ts where they are derived directly from token values.
//
// Types are no longer generated by Style Dictionary. Instead, we use TypeScript's
// `typeof` operator with the GetTypes utility to extract types from the actual
// token values. This ensures types are always accurate and in sync.
// ============================================================================

export type { Theme, CUIThemeType, ThemeName, PublicTheme } from '@/theme';
