#!/bin/bash

if [[ -d ./dist ]]; then
  if ! rm -rf ./dist; then
    echo "Failed to delete dist directory"
  fi
fi

if ! yarn typecheck; then
  echo "Error: found typescript issues"

  exit 1
fi

if ! vite build; then
  echo "Error: failed to build the package"

  exit 1
fi

if ! .scripts/js/generate-exports; then
  echo "Error: failed to generate exports"

  exit 1
fi

# Always run the health check locally
# but the health check is a separate step on CI
if [[ -z "$CI" ]]; then
  yarn build:health_check
fi
