export type AssetAliasMap = Record<string, string>;
export type AssetAlias = keyof typeof ASSET_NAME_MAPPINGS.aliases;

/**
 * @deprecated Use the kebab-case name instead (e.g., 'activity' instead of 'Activity')
 */
export type AssetDeprecatedName = keyof typeof ASSET_NAME_MAPPINGS.deprecated;

export const ASSET_NAME_MAPPINGS = {
  aliases: {
    'c#': 'c-sharp',
  } as AssetAliasMap,

  deprecated: {
    Activity: 'activity',
    Alarm: 'alarm',
    ArrowDirections: 'arrow-directions',
    ArrowDown: 'arrow-down',
    ArrowLeft: 'arrow-left',
    ArrowRight: 'arrow-right',
    ArrowTriangle: 'arrow-triangle',
    ArrowUp: 'arrow-up',
    AuthApp: 'auth-app',
    AuthSms: 'auth-sms',
    Backups: 'backups',
    BarChart: 'bar-chart',
    Bell: 'bell',
    Beta: 'beta',
    Blog: 'blog',
    Bold: 'bold',
    Book: 'book',
    Brackets: 'brackets',
    Briefcase: 'briefcase',
    Building: 'building',
    BurgerMenu: 'burger-menu',
    Calendar: 'calendar',
    CalendarWithTime: 'calendar-with-time',
    Cards: 'cards',
    CellTower: 'cell-tower',
    ChartArea: 'chart-area',
    ChartBarHorizontal: 'chart-bar-horizontal',
    ChartCloud: 'chart-cloud',
    ChartDonut: 'chart-donut',
    ChartHeatmap: 'chart-heatmap',
    ChartScatter: 'chart-scatter',
    ChartSquare: 'chart-square',
    ChartStackedHorizontal: 'chart-stacked-horizontal',
    ChartStackedVertical: 'chart-stacked-vertical',
    ChatIcon: 'chat',
    CheckIcon: 'check',
    CheckInCircle: 'check-in-circle',
    ChevronDown: 'chevron-down',
    ChevronLeft: 'chevron-left',
    ChevronRight: 'chevron-right',
    ChevronUp: 'chevron-up',
    Circle: 'circle',
    Clock: 'clock',
    Cloud: 'cloud',
    CloudKeys: 'cloud-keys',
    Code: 'code',
    CodeInSquare: 'code-in-square',
    Connect: 'connect',
    ConnectAlt: 'connect-alt',
    Console: 'console',
    Copy: 'copy',
    Cpu: 'cpu',
    CreditCard: 'credit-card',
    CrossIcon: 'cross',
    Data: 'data',
    DataLakes: 'data-lakes',
    DatabaseIcon: 'database',
    Disk: 'disk',
    Display: 'display',
    Document: 'document',
    Dot: 'dot',
    DotsHorizontal: 'dots-horizontal',
    DotsTriangle: 'dots-triangle',
    DotsVertical: 'dots-vertical',
    DotsVerticalDouble: 'dots-vertical-double',
    DoubleCheckIcon: 'double-check',
    Download: 'download',
    DownloadInCircle: 'download-in-circle',
    Email: 'email',
    Empty: 'empty',
    Enter: 'enter',
    Eye: 'eye',
    EyeClosed: 'eye-closed',
    FilterIcon: 'filter',
    Fire: 'fire',
    Flag: 'flag',
    Flash: 'flash',
    Flask: 'flask',
    FolderClosed: 'folder-closed',
    FolderOpen: 'folder-open',
    Gear: 'gear',
    Gift: 'gift',
    GitMerge: 'git-merge',
    Globe: 'globe',
    Hexagon: 'hexagon',
    HistoryIcon: 'history',
    Home: 'home',
    HorizontalLoading: 'horizontal-loading',
    Http: 'http',
    HttpMonitoring: 'http-monitoring',
    InfoInCircleIcon: 'info-in-circle',
    InformationIcon: 'information',
    InsertRowIcon: 'insert-row',
    Integrations: 'integrations',
    Italic: 'italic',
    Key: 'key',
    Keys: 'keys',
    Lifebuoy: 'lifebuoy',
    LightBulb: 'light-bulb',
    LightBulbOn: 'light-bulb-on',
    Lightening: 'lightening',
    LineInCircle: 'line-in-circle',
    ListBulleted: 'list-bulleted',
    ListNumbered: 'list-numbered',
    Loading: 'loading',
    LoadingAnimated: 'loading-animated',
    Lock: 'lock',
    MapPin: 'map-pin',
    Mcp: 'mcp',
    Metrics: 'metrics',
    MetricsAlt: 'metrics-alt',
    Minus: 'minus',
    Moon: 'moon',
    NoCloud: 'no-cloud',
    Pause: 'pause',
    Payment: 'payment',
    Pencil: 'pencil',
    PieChart: 'pie-chart',
    Pipe: 'pipe',
    Play: 'play',
    PlayInCircle: 'play-in-circle',
    Plug: 'plug',
    Plus: 'plus',
    Popout: 'popout',
    PopoverArrow: 'popover-arrow',
    PuzzlePiece: 'puzzle-piece',
    Query: 'query',
    Question: 'question',
    Refresh: 'refresh',
    ResizeArrowsHorizontal: 'resize-arrows-horizontal',
    ResizeArrowsVertical: 'resize-arrows-vertical',
    Rocket: 'rocket',
    SandGlass: 'sand-glass',
    Search: 'search',
    Secure: 'secure',
    Server: 'server',
    Services: 'services',
    Settings: 'settings',
    Share: 'share',
    ShareArrow: 'share-arrow',
    ShareNetwork: 'share-network',
    Sleep: 'sleep',
    SlideIn: 'slide-in',
    SlideOut: 'slide-out',
    SortAltIcon: 'sort-alt',
    SortIcon: 'sort',
    Sparkle: 'sparkle',
    Speaker: 'speaker',
    Speed: 'speed',
    Square: 'square',
    Star: 'star',
    Stop: 'stop',
    Support: 'support',
    Table: 'table',
    Taxi: 'taxi',
    TextSlash: 'text-slash',
    ThumbsDown: 'thumbs-down',
    ThumbsUp: 'thumbs-up',
    Trash: 'trash',
    TreeStructure: 'tree-structure',
    Underline: 'underline',
    Upgrade: 'upgrade',
    Upload: 'upload',
    Url: 'url',
    UserIcon: 'user',
    UsersIcon: 'users',
    WarningIcon: 'warning',
    Waves: 'waves',

    // Flag deprecations (from retroactiveNames.ts)
    ae: 'united-arab-emirates',
    au: 'australia',
    br: 'brazil',
    ca: 'canada',
    ch: 'switzerland',
    de: 'germany',
    eu: 'european-union',
    gb: 'great-britain',
    hk: 'hong-kong',
    id: 'indonesia',
    ie: 'ireland',
    il: 'israel',
    in: 'india',
    jp: 'japan',
    nl: 'netherlands',
    sg: 'singapore',
    kr: 'south-korea',
    sw: 'sweden',
    uk: 'united-kingdom',
    usa: 'united-states',
    za: 'south-africa',
    Australia: 'australia',
    Brazil: 'brazil',
    Canada: 'canada',
    EuropeanUnion: 'european-union',
    Germany: 'germany',
    GreatBritain: 'great-britain',
    HongKong: 'hong-kong',
    India: 'india',
    Indonesia: 'indonesia',
    Ireland: 'ireland',
    Israel: 'israel',
    Japan: 'japan',
    Netherlands: 'netherlands',
    Singapore: 'singapore',
    SouthAfrica: 'south-africa',
    SouthKorea: 'south-korea',
    Sweden: 'sweden',
    Switzerland: 'switzerland',
    UnitedArabEmirates: 'united-arab-emirates',
    UnitedKingdom: 'united-kingdom',
    UnitedStates: 'united-states',
  } as AssetAliasMap,
} as const;

export const resolveAssetName = (name: string): string => {
  if (ASSET_NAME_MAPPINGS.aliases[name]) {
    return ASSET_NAME_MAPPINGS.aliases[name];
  }

  if (ASSET_NAME_MAPPINGS.deprecated[name]) {
    console.warn(
      `Asset name "${name}" is deprecated, use "${ASSET_NAME_MAPPINGS.deprecated[name]}" instead`
    );

    return ASSET_NAME_MAPPINGS.deprecated[name];
  }

  return name;
};

export const createAssetResolver = <T extends string>() => {
  return (name: string): T => resolveAssetName(name) as T;
};
