import React from "react";
import type { ThemeName } from "@/theme/types";

interface ServerClickUIProviderProps {
  children: React.ReactNode;
  theme?: ThemeName; // "light" | "dark" | "system"
  /**
   * Theme variation to use. Currently only "default" is supported.
   * Future variations may include "contrast" for high-contrast themes.
   * @default "default"
   */
  variation?: "default";
}

/**
 * Server-side Click UI Provider
 *
 * IMPORTANT: CSS must be imported in your app:
 * - With custom theme: import './cui-custom-theme.css' (generated by CLI)
 * - With default theme: import '@clickhouse/click-ui/dist/cui-default-theme.css'
 *
 * This provider only sets the theme attribute and color-scheme.
 * All theme CSS is pre-built and loaded via imports.
 *
 * **Changed in v0.1.0:** Toast and Tooltip providers removed to enable true RSC support.
 * Use ClickUIProviders separately for Toast/Tooltip functionality.
 *
 * @example
 * ```tsx
 * // Recommended pattern for Next.js App Router
 * import { ServerClickUIProvider, ClickUIProviders } from '@clickhouse/click-ui';
 *
 * export default function RootLayout({ children }) {
 *   return (
 *     <html>
 *       <body>
 *         <ServerClickUIProvider theme="system" variation="default">
 *           <ClickUIProviders>
 *             {children}
 *           </ClickUIProviders>
 *         </ServerClickUIProvider>
 *       </body>
 *     </html>
 *   );
 * }
 * ```
 */
export const ServerClickUIProvider = ({
  children,
  theme = "light",
  variation = "default",
}: ServerClickUIProviderProps) => {
  // Set color-scheme based on theme prop
  const isSystemMode = theme === "system";
  const colorScheme = isSystemMode ? "light dark" : theme === "dark" ? "dark" : "light";

  return (
    <>
      <style
        dangerouslySetInnerHTML={{
          __html: `:root { color-scheme: ${colorScheme}; }`,
        }}
      />
      <div
        data-theme={theme}
        data-variation={variation}
      >
        {children}
      </div>
    </>
  );
};
