import React from "react";
import type { ThemeName } from "@/theme/types";
import {
  Provider as TooltipProvider,
  TooltipProviderProps,
} from "@radix-ui/react-tooltip";
import { ToastProvider, ToastProviderProps } from "@/components/Toast/Toast";

interface ServerClickUIProviderProps {
  children: React.ReactNode;
  theme?: ThemeName; // "light" | "dark" | "system"
  // ClickUI specific props
  tooltipConfig?: Omit<TooltipProviderProps, "children">;
  toastConfig?: Omit<ToastProviderProps, "children">;
}

/**
 * Server-side Click UI Provider
 *
 * IMPORTANT: CSS must be imported in your app:
 * - With custom theme: import './cui-custom-theme.css' (generated by CLI)
 * - With default theme: import '@clickhouse/click-ui/dist/cui-default-theme.css'
 *
 * This provider only sets the theme attribute and provides context.
 * All theme CSS is pre-built and loaded via imports.
 */
export const ServerClickUIProvider = ({
  children,
  theme = "light",
  tooltipConfig = {},
  toastConfig = {},
}: ServerClickUIProviderProps) => {
  // Set color-scheme based on theme prop
  const isSystemMode = theme === "system";
  const colorScheme = isSystemMode ? "light dark" : theme === "dark" ? "dark" : "light";

  return (
    <>
      <style
        dangerouslySetInnerHTML={{
          __html: `:root { color-scheme: ${colorScheme}; }`,
        }}
      />
      <div data-theme={theme}>
        <ToastProvider {...toastConfig}>
          <TooltipProvider {...tooltipConfig}>{children}</TooltipProvider>
        </ToastProvider>
      </div>
    </>
  );
};
