import { IconName } from './types';

export type DeprecatedIconName =
  | 'Activity'
  | 'Alarm'
  | 'ArrowDirections'
  | 'ArrowDown'
  | 'ArrowLeft'
  | 'ArrowRight'
  | 'ArrowTriangle'
  | 'ArrowUp'
  | 'AuthApp'
  | 'AuthSms'
  | 'Backups'
  | 'BarChart'
  | 'Bell'
  | 'Beta'
  | 'Blog'
  | 'Bold'
  | 'Book'
  | 'Brackets'
  | 'Briefcase'
  | 'Building'
  | 'BurgerMenu'
  | 'Calendar'
  | 'CalendarWithTime'
  | 'Cards'
  | 'CellTower'
  | 'ChartArea'
  | 'ChartBarHorizontal'
  | 'ChartCloud'
  | 'ChartDonut'
  | 'ChartHeatmap'
  | 'ChartScatter'
  | 'ChartSquare'
  | 'ChartStackedHorizontal'
  | 'ChartStackedVertical'
  | 'ChatIcon'
  | 'CheckIcon'
  | 'CheckInCircle'
  | 'ChevronDown'
  | 'ChevronLeft'
  | 'ChevronRight'
  | 'ChevronUp'
  | 'Circle'
  | 'Clock'
  | 'Cloud'
  | 'CloudKeys'
  | 'Code'
  | 'CodeInSquare'
  | 'Connect'
  | 'ConnectAlt'
  | 'Console'
  | 'Copy'
  | 'Cpu'
  | 'CreditCard'
  | 'CrossIcon'
  | 'Data'
  | 'DataLakes'
  | 'DatabaseIcon'
  | 'Disk'
  | 'Display'
  | 'Document'
  | 'Dot'
  | 'DotsHorizontal'
  | 'DotsTriangle'
  | 'DotsVertical'
  | 'DotsVerticalDouble'
  | 'DoubleCheckIcon'
  | 'Download'
  | 'DownloadInCircle'
  | 'Email'
  | 'Empty'
  | 'Enter'
  | 'Eye'
  | 'EyeClosed'
  | 'FilterIcon'
  | 'Fire'
  | 'Flag'
  | 'Flash'
  | 'Flask'
  | 'FolderClosed'
  | 'FolderOpen'
  | 'Gear'
  | 'Gift'
  | 'GitMerge'
  | 'Globe'
  | 'Hexagon'
  | 'HistoryIcon'
  | 'Home'
  | 'HorizontalLoading'
  | 'Http'
  | 'HttpMonitoring'
  | 'InfoInCircleIcon'
  | 'InformationIcon'
  | 'InsertRowIcon'
  | 'Integrations'
  | 'Italic'
  | 'Key'
  | 'Keys'
  | 'Lifebuoy'
  | 'LightBulb'
  | 'LightBulbOn'
  | 'Lightening'
  | 'LineInCircle'
  | 'ListBulleted'
  | 'ListNumbered'
  | 'Loading'
  | 'LoadingAnimated'
  | 'Lock'
  | 'MapPin'
  | 'Mcp'
  | 'Metrics'
  | 'MetricsAlt'
  | 'Minus'
  | 'Moon'
  | 'NoCloud'
  | 'Pause'
  | 'Payment'
  | 'Pencil'
  | 'PieChart'
  | 'Pipe'
  | 'Play'
  | 'PlayInCircle'
  | 'Plug'
  | 'Plus'
  | 'Popout'
  | 'PopoverArrow'
  | 'PuzzlePiece'
  | 'Query'
  | 'Question'
  | 'Refresh'
  | 'ResizeArrowsHorizontal'
  | 'ResizeArrowsVertical'
  | 'Rocket'
  | 'SandGlass'
  | 'Search'
  | 'Secure'
  | 'Server'
  | 'Services'
  | 'Settings'
  | 'Share'
  | 'ShareArrow'
  | 'ShareNetwork'
  | 'Sleep'
  | 'SlideIn'
  | 'SlideOut'
  | 'SortAltIcon'
  | 'SortIcon'
  | 'Sparkle'
  | 'Speaker'
  | 'Speed'
  | 'Square'
  | 'Star'
  | 'Stop'
  | 'Support'
  | 'Table'
  | 'Taxi'
  | 'TextSlash'
  | 'ThumbsDown'
  | 'ThumbsUp'
  | 'Trash'
  | 'TreeStructure'
  | 'Underline'
  | 'Upgrade'
  | 'Upload'
  | 'Url'
  | 'UserIcon'
  | 'UsersIcon'
  | 'WarningIcon'
  | 'Waves';

export const ICON_NAME_RETRO_MAP: Record<DeprecatedIconName, IconName> = {
  Activity: 'activity',
  Alarm: 'alarm',
  ArrowDirections: 'arrow-directions',
  ArrowDown: 'arrow-down',
  ArrowLeft: 'arrow-left',
  ArrowRight: 'arrow-right',
  ArrowTriangle: 'arrow-triangle',
  ArrowUp: 'arrow-up',
  AuthApp: 'auth-app',
  AuthSms: 'auth-sms',
  Backups: 'backups',
  BarChart: 'bar-chart',
  Bell: 'bell',
  Beta: 'beta',
  Blog: 'blog',
  Bold: 'bold',
  Book: 'book',
  Brackets: 'brackets',
  Briefcase: 'briefcase',
  Building: 'building',
  BurgerMenu: 'burger-menu',
  Calendar: 'calendar',
  CalendarWithTime: 'calendar-with-time',
  Cards: 'cards',
  CellTower: 'cell-tower',
  ChartArea: 'chart-area',
  ChartBarHorizontal: 'chart-bar-horizontal',
  ChartCloud: 'chart-cloud',
  ChartDonut: 'chart-donut',
  ChartHeatmap: 'chart-heatmap',
  ChartScatter: 'chart-scatter',
  ChartSquare: 'chart-square',
  ChartStackedHorizontal: 'chart-stacked-horizontal',
  ChartStackedVertical: 'chart-stacked-vertical',
  ChatIcon: 'chat',
  CheckIcon: 'check',
  CheckInCircle: 'check-in-circle',
  ChevronDown: 'chevron-down',
  ChevronLeft: 'chevron-left',
  ChevronRight: 'chevron-right',
  ChevronUp: 'chevron-up',
  Circle: 'circle',
  Clock: 'clock',
  Cloud: 'cloud',
  CloudKeys: 'cloud-keys',
  Code: 'code',
  CodeInSquare: 'code-in-square',
  Connect: 'connect',
  ConnectAlt: 'connect-alt',
  Console: 'console',
  Copy: 'copy',
  Cpu: 'cpu',
  CreditCard: 'credit-card',
  CrossIcon: 'cross',
  Data: 'data',
  DataLakes: 'data-lakes',
  DatabaseIcon: 'database',
  Disk: 'disk',
  Display: 'display',
  Document: 'document',
  Dot: 'dot',
  DotsHorizontal: 'dots-horizontal',
  DotsTriangle: 'dots-triangle',
  DotsVertical: 'dots-vertical',
  DotsVerticalDouble: 'dots-vertical-double',
  DoubleCheckIcon: 'double-check',
  Download: 'download',
  DownloadInCircle: 'download-in-circle',
  Email: 'email',
  Empty: 'empty',
  Enter: 'enter',
  Eye: 'eye',
  EyeClosed: 'eye-closed',
  FilterIcon: 'filter',
  Fire: 'fire',
  Flag: 'flag',
  Flash: 'flash',
  Flask: 'flask',
  FolderClosed: 'folder-closed',
  FolderOpen: 'folder-open',
  Gear: 'gear',
  Gift: 'gift',
  GitMerge: 'git-merge',
  Globe: 'globe',
  Hexagon: 'hexagon',
  HistoryIcon: 'history',
  Home: 'home',
  HorizontalLoading: 'horizontal-loading',
  Http: 'http',
  HttpMonitoring: 'http-monitoring',
  InfoInCircleIcon: 'info-in-circle',
  InformationIcon: 'information',
  InsertRowIcon: 'insert-row',
  Integrations: 'integrations',
  Italic: 'italic',
  Key: 'key',
  Keys: 'keys',
  Lifebuoy: 'lifebuoy',
  LightBulb: 'light-bulb',
  LightBulbOn: 'light-bulb-on',
  Lightening: 'lightening',
  LineInCircle: 'line-in-circle',
  ListBulleted: 'list-bulleted',
  ListNumbered: 'list-numbered',
  Loading: 'loading',
  LoadingAnimated: 'loading-animated',
  Lock: 'lock',
  MapPin: 'map-pin',
  Mcp: 'mcp',
  Metrics: 'metrics',
  MetricsAlt: 'metrics-alt',
  Minus: 'minus',
  Moon: 'moon',
  NoCloud: 'no-cloud',
  Pause: 'pause',
  Payment: 'payment',
  Pencil: 'pencil',
  PieChart: 'pie-chart',
  Pipe: 'pipe',
  Play: 'play',
  PlayInCircle: 'play-in-circle',
  Plug: 'plug',
  Plus: 'plus',
  Popout: 'popout',
  PopoverArrow: 'popover-arrow',
  PuzzlePiece: 'puzzle-piece',
  Query: 'query',
  Question: 'question',
  Refresh: 'refresh',
  ResizeArrowsHorizontal: 'resize-arrows-horizontal',
  ResizeArrowsVertical: 'resize-arrows-vertical',
  Rocket: 'rocket',
  SandGlass: 'sand-glass',
  Search: 'search',
  Secure: 'secure',
  Server: 'server',
  Services: 'services',
  Settings: 'settings',
  Share: 'share',
  ShareArrow: 'share-arrow',
  ShareNetwork: 'share-network',
  Sleep: 'sleep',
  SlideIn: 'slide-in',
  SlideOut: 'slide-out',
  SortAltIcon: 'sort-alt',
  SortIcon: 'sort',
  Sparkle: 'sparkle',
  Speaker: 'speaker',
  Speed: 'speed',
  Square: 'square',
  Star: 'star',
  Stop: 'stop',
  Support: 'support',
  Table: 'table',
  Taxi: 'taxi',
  TextSlash: 'text-slash',
  ThumbsDown: 'thumbs-down',
  ThumbsUp: 'thumbs-up',
  Trash: 'trash',
  TreeStructure: 'tree-structure',
  Underline: 'underline',
  Upgrade: 'upgrade',
  Upload: 'upload',
  Url: 'url',
  UserIcon: 'user',
  UsersIcon: 'users',
  WarningIcon: 'warning',
  Waves: 'waves',
};

export const resolveIconName = (name: string): IconName => {
  const mapped = (ICON_NAME_RETRO_MAP as Record<string, IconName>)[name];
  if (mapped) {
    console.warn(`Icon name "${name}" is deprecated, use "${mapped}" instead`);
    return mapped;
  }
  return name as IconName;
};
