import type { SVGAttributes } from 'react';
import type { AssetSize } from '@/types';
import type { ThemeName } from '@/theme/theme.types';

export type LogoName =
  | 'airbyte'
  | 'alloydb'
  | 'apache-iceberg'
  | 'aws'
  | 'aws-athena'
  | 'aws-aurora'
  | 'aws-glue'
  | 'aws-kinesis'
  | 'aws-msk'
  | 'aws-rds'
  | 'aws-redshift'
  | 'aws-s3'
  | 'azure'
  | 'azure-blob-storage'
  | 'azure-event-hub'
  | 'bigquery'
  | 'clickhouse'
  | 'cloudflare'
  | 'confluent'
  | 'crunchy-bridge'
  | 'csharp'
  | 'databricks'
  | 'datagrip'
  | 'dbeaver'
  | 'dbt'
  | 'decodeable'
  | 'deepnote'
  | 'deltalake'
  | 'digitalocean'
  | 'feature-database'
  | 'feature-hexagon'
  | 'fivetran'
  | 'gcp'
  | 'gcs'
  | 'github'
  | 'golang'
  | 'google'
  | 'grafana'
  | 'hex'
  | 'hudi'
  | 'iceberg'
  | 'jdbc'
  | 'kafka'
  | 'kubernetes'
  | 'lakekeeper'
  | 'mariadb'
  | 'metabase'
  | 'microsoft'
  | 'mongodb'
  | 'mysql'
  | 'neondb'
  | 'nessie'
  | 'nodejs'
  | 'onelake'
  | 'ovh'
  | 'planetscale'
  | 'postgres'
  | 'prequel'
  | 'python'
  | 'redpanda'
  | 'rust'
  | 'snowflake'
  | 'supabase'
  | 'superset'
  | 'tableau'
  | 'tigerdata'
  | 'upstash'
  | 'vector'
  | 'warpstream';

export interface LogoProps extends SVGAttributes<SVGElement> {
  name: LogoName;
  theme?: ThemeName;
  size?: AssetSize;
}
