import type { SVGAttributes } from 'react';
import type { AssetSize } from '@/types';
import type { ThemeName } from '@/theme/theme.types';

export type LogoName =
  | 'airbyte'
  | 'alloy-db'
  | 'aws'
  | 'aws-athena'
  | 'aws-aurora'
  | 'aws-glue'
  | 'aws-kinesis'
  | 'aws-msk'
  | 'aws-rds'
  | 'aws-redshift'
  | 'aws-s3'
  | 'azure'
  | 'azure-blob-storage'
  | 'azure-event-hub'
  | 'big-query'
  | 'c-sharp'
  | 'clickhouse'
  | 'cloudflare'
  | 'confluent'
  | 'crunchy-bridge'
  | 'd-beaver'
  | 'data-grip'
  | 'databricks'
  | 'dbt'
  | 'decodeable'
  | 'deep-note'
  | 'delta-lake'
  | 'digital-ocean'
  | 'feature-database'
  | 'feature-hexagon'
  | 'fivetran'
  | 'gcp'
  | 'gcs'
  | 'github'
  | 'go-lang'
  | 'google'
  | 'grafana'
  | 'hex'
  | 'hudi'
  | 'iceberg'
  | 'jdbc'
  | 'kafka'
  | 'kubenetes'
  | 'maria-db'
  | 'metabase'
  | 'microsoft'
  | 'mongo-db'
  | 'my-sql'
  | 'neon-db'
  | 'nessie'
  | 'node-js'
  | 'one-lake'
  | 'ovh'
  | 'planet-scale'
  | 'postgres'
  | 'prequel'
  | 'python'
  | 'redpanda'
  | 'rust'
  | 'snowflake'
  | 'supabase'
  | 'superset'
  | 'tableau'
  | 'tiger-data'
  | 'upstash'
  | 'vector'
  | 'warp-stream';

export interface LogoProps extends SVGAttributes<SVGElement> {
  name: LogoName;
  theme?: ThemeName;
  size?: AssetSize;
}
