#!/bin/bash

if ! yarn typecheck; then
  echo "👹 Oops! Found typescript issues..."

  exit 1
fi

if ! vite build; then
  echo "👹 Oops! Failed to build the package..."

  exit 1
fi

# Always run the health check locally
# but the health check is a separate step on CI
if [[ -z "$CI" ]]; then
  yarn build:health_check
fi
