#!/bin/bash

if [[ -n "$CI" ]]; then
  echo "🦖 Skipped! Running in CI environment."
  exit 0
fi

echo "🚑 Health check, please be patient..."
echo

if yarn test; then
  echo "✅ Tests passed!"
else
  echo "👹 Oops, tests failed! Fix it before committing, please!"
  exit 1
fi

if yarn format; then
  echo "✅ Code format checked!"
else
  echo "⚠️ WARNING: Incorrect code format, fix it before committing, please!"
  echo "💡 Use the command yarn format:fix"
  exit 1
fi

if yarn lint; then
  echo "✅ Linter check is good!"
else
  echo "⚠️ WARNING: Linter found issues, fix them before committing, please!"
  echo "💡 Use the command yarn lint:fix"
  exit 1
fi

if yarn workspace @clickhouse/click-ui circular-dependency:check; then
  echo "✅ Circular dependency check is good!"
else
  echo "⚠️ WARNING: Circular dependency checkup found issues, fix them before committing, please!"
  echo "💡 Use the following command to get further reports in your resolution yarn workspace @clickhouse/click-ui circular-dependency:check"
  exit 1
fi

if yarn workspace @clickhouse/click-ui changeset:verify; then
  echo "✅ Changeset file's included!"
else
  echo "⚠️ WARNING: You must include a changeset!"
  echo "💡 Use the command yarn workspace @clickhouse/click-ui changeset:add"
  exit 1
fi

echo "👍 Health check completed."
echo
