name: 🔔 Pull Request Slack notification

on:
  pull_request:
    types: [opened]

jobs:
  notify-slack:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Prepare PR description
        id: prepare
        run: |
          DESC=$(.scripts/pull-request-truncate-body "${{ github.event.pull_request.body }}")

          echo "description=$DESC" >> $GITHUB_OUTPUT

      - name: Notify Slack about new PR
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: "${{ secrets.SLACK_CHANNEL }}"
            text: "===\n🔔 ${{ secrets.SLACK_GROUP_TAG_NAME_FOR_CUI_NOTIFICATIONS }} *New Pull Request Opened*\n\n*Title:* ${{ github.event.pull_request.title }}\n*Author:* @${{ github.event.pull_request.user.login }}\n*Branch:* ${{ github.event.pull_request.head.ref }} → ${{ github.event.pull_request.base.ref }}\n\n*Description:*\n${{ steps.prepare.outputs.description }}\n\n<${{ github.event.pull_request.html_url }}|View Pull Request>\n==="
